<?php
/*
  implements hook_menu()
*/
function menu_magic_menu() {
  $items = array();

  $items['magic'] = array(
    'title' => 'A title magic',
    'page callback' => 'menu_magic_basic',
    'access callback' => 'user_access', // drupal default user callback
    'access arguments' => array('access content'), //checks if access box is checked for user
  );

  //url with variable in it %
  $items['magic/%'] = array(
    'title' => 'Even more magic',
    'page callback' => 'menu_magic_extra',
    'page arguments' => array(1), //pass second array url variable as argument
    'access callback' => 'user_access', // drupal default user callback
    'access arguments' => array('access content'), //checks if access box is checked for user,
    'file' => 'menu_magic.extra.inc', //similar to php include
  );

  //url with variable in it %
  $items['user/%/magic'] = array(
    'title' => 'Magic',
    'description' => 'This will display a variable fromt he url',
    'page callback' => 'menu_magic_user_tab',
    'page arguments' => array(1), //pass second array url variable as argument
    'access callback' => 'user_access', // drupal default user callback
    'access arguments' => array('administer users'), //checks if access box is checked for user,
    'file' => 'menu_magic.user.inc', //similar to php include
    'type' => MENU_LOCAL_TASK, //type of menu item
  );

  $items['node/%node/magic'] = array(
    'title' => 'Magic',
    'description' => 'Do amazing and magical things',
    'page callback' => 'menu_magic_node_context',
    'page arguments' => array(1), //pass second url segments as argument
    'access callback' => 'user_access', // drupal default user callback
    'access arguments' => array('access content'), //all users have access,
    'file' => 'menu_magic.context.inc', //similar to php include
    'type' => MENU_LOCAL_TASK, //type of menu item
    'context' => MENU_CONTEXT_PAGE | MENU_CONTEXT_INLINE, //place link in both
  );

  return $items;
}


// callback function for hook_menu
function menu_magic_basic(){
  $content = array();
  $content['raw_markup'] = array (
    '#type' => 'markup',
    '#markup' => t('This is truly magic'),
    '#prefix' => '<p>',
    '#suffix' => '</p>',
  );

  $vars = array(
    'path' => 'http://placehold.it/400x400',
    'alt' => t('This is a magic kitten'),
    'title' => t('this is a title'),
  );

  $content['themed_data'] = array(
    '#type' => 'markup',
    '#markup' => theme('image', $vars),
    '#prefix' => '<div class="menu-magic-img-wrap">',
    '#suffix' => '</div>',
    '#attached' => array(
      'css' => array(
        drupal_get_path('module', 'menu_magic'). '/menu_magic.css',
      ),
    ),
  );

  $content['renderable_element'] = array(
    '#theme' => 'item_list',
    '#title' => t('How do we know it\'s magic? '),
    '#items' => array(
      t('Is it made of wood?'),
      t('Does it float in the lake?'),
      t('Does it weigh the same as a duck or swallow'),
      t('The current time is %time.', array('%time' => date('r'))),
    ),
    '#cache' => array(
      'keys' => array('menu_magic', 'renderable_element'),
      'bin' => 'cache',
      'expire' => time() + 30,
      'granularity' => DRUPAL_CACHE_PER_PAGE,
    ),
  );


  return $content;
}
